### PR TITLE
Fix crash caused by use of `try!` while installing invalid version

### LINKED ISSUE #72: `carton sdk install` crashes when passed an invalid version
```
% carton sdk install blah                                                                                                                                   
Fetching release assets from https://api.github.com/repos/swiftwasm/swift/releases/tags/swift-blah
Fatal error: 'try!' expression unexpectedly raised an error: Swift.DecodingError.keyNotFound(CodingKeys(stringValue: "assets", intValue: nil), Swift.DecodingError.Context(codingPath: [], debugDescription: "No value associated with key CodingKeys(stringValue: \"assets\", intValue: nil) (\"assets\").", underlyingError: nil)): file /private/tmp/carton-20200722-22952-1js7ud6/carton-0.4.1/Sources/SwiftToolchain/ToolchainManagement.swift, line 132
zsh: illegal hardware instruction  carton sdk install blah
```

### PR DESCRIPTION
**Pull request by RayZhao1998**
Fix #72.

If you are installing an invalid version, It'll now throw an `InvalidVersion` error and the output will be more friendly.

### CODE REVIEW

File: Sources/SwiftToolchain/ToolchainManagement.swift [hunk 1]
```diff
@@ -231,7 +230,8 @@ extension FileSystem {
     } else if let inferredURL = try inferDownloadURL(from: swiftVersion, client, terminal) {
       downloadURL = inferredURL
     } else {
-      fatalError("Failed to infer download URL for version \(swiftVersion)")
+      terminal.write("The Swift version \(swiftVersion) not found\n", inColor: .red)
```
Comment (MaxDesiatov) [inline Sources/SwiftToolchain/ToolchainManagement.swift:233]:
```suggestion
      terminal.write("The Swift version \(swiftVersion) was not found\n", inColor: .red)
```
