### PR TITLE
Close WebSocket connections after HTTP server exits

### LINKED ISSUE #7: Delay on Ctrl-C with error: Could not stop HTTP server
Currently, when attempting to stop the command-line invocation of `carton` with Ctrl-C, you get this error:

```
[ ERROR ] Could not stop HTTP server: Abort(identifier: "500", status: 
NIOHTTP1.HTTPResponseStatus.internalServerError, headers: , 
reason: "Server stop took too long.", 
source: Vapor.ErrorSource(file: "/private/tmp/carton-20200616-45672-cfefqh/carton-0.1.0/.build/checkouts/vapor/Sources/Vapor/HTTP/Server/HTTPServer.swift", function: "close()", line: 310, column: 31, range: nil))
ERROR: Cannot schedule tasks on an EventLoop that has already shut down. 
This will be upgraded to a forced crash in future SwiftNIO versions.
```

According to SwiftNIO, this doesn't seem to be an issue with SwiftNIO, probably caused by how Vapor uses their API. Upgrading to the latest version of Vapor is blocked by https://github.com/vapor/vapor/issues/2385

### PR DESCRIPTION
**Pull request by MaxDesiatov**
Resolve #7 as described in https://github.com/vapor/vapor/issues/2451.

Additionaly, new formatting is applied with the new version of SwiftFormat.

### CODE REVIEW

File: Sources/SwiftToolchain/ToolchainManagement.swift [hunk 1]
```diff
@@ -78,7 +78,8 @@ extension FileSystem {
     if let versionSpec = versionSpec {
       if let url = URL(string: versionSpec),
         let filename = url.pathComponents.last,
-        let match = versionRegEx.matchGroups(in: filename).first?.first {
+        let match = versionRegEx.matchGroups(in: filename).first?.first
+      {
```
Comment (ie-ahm-robox) [inline Sources/SwiftToolchain/ToolchainManagement.swift:82]: - :no_entry_sign: Opening braces should be preceded by a single space and on the same line as the declaration. (`opening_brace`)

**Comment by ie-ahm-robox** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  **Sources/SwiftToolchain/FileDownloadDelegate.swift#L54** - Opening braces should be preceded by a single space and on the same line as the declaration. (`opening_brace`)
  </td>
    </tr>
  </tbody>
</table>




<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/swift">Danger Swift</a> against c3f6a64c3fbc5d42d7220db08f9d7d74a57155a1
</p>
